// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsowliifibqtgracbpgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzb3dsaWlmaWJxdGdyYWNicGd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMDU4NDcsImV4cCI6MjA3MjY4MTg0N30._JHoZakd8YFTM7yzK5Y1MsWCgpp934Ls5vUey6CeCRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});